spring:
  data:
    mongodb:
      database: demo
      host: localhost
      port: 27017
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
  mail:
    default-encoding: utf-8
    host: smtp.yeah.net
    password: TRYOAEHEKOLVOXGX
    username: springcloud_mail@yeah.net
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

jwt:
  expiration: 604800
  secret: CompetitiveLin

logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs

minio:
  accessKey: minioadmin
  bucketName: demo
  endpoint: http://localhost:9000
  secretKey: minioadmin

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: is_deleted