spring:
  data:
    mongodb:
      database: demo
      host: localhost
      port: 27017
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
  mail:
    default-encoding: utf-8
    host: smtp.yeah.net
    password: TRYOAEHEKOLVOXGX
    username: springcloud_mail@yeah.net
  #  main:
  #    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: ''
    port: 6379
    timeout: 1000ms
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  elasticsearch:
    uris: localhost:9200

jwt:
  expiration: 604800
  secret: CompetitiveLin

logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs
    name: slf4j-test

minio:
  accessKey: minioadmin
  bucketName: demo
  endpoint: http://localhost:9000
  secretKey: minioadmin

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: is_deleted

rocketmq:
  name-server: localhost:9876
  producer:
    group: rocketmq-producer
    # 消息发送超时时长，默认3s
    send-message-timeout: 3000
    # 同步发送消息失败重试次数，默认2
    retry-times-when-send-failed: 3
    # 异步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3
  consumer:
    # 一次拉取消息最大值，注意是拉取消息的最大值而非消费最大值
    pull-batch-size: 10