version: '3.5'
services:
  mysql:
    image: mysql:latest
    container_name: demo-mysql
    volumes:
      - C:\Users\CompetitiveLin\Documents\Volume\mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    command:
      --log-bin=mysql-bin
      --binlog-format=ROW
      --server_id=1
  
  redis:
    image: redis:latest
    container_name: demo-redis
    volumes:
      - C:\Users\CompetitiveLin\Documents\Volume\redis:/data
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    container_name: demo-minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - C:\Users\CompetitiveLin\Documents\Volume\minio:/data
    command: server /data --console-address ":9090"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin

  mongodb:
    image: mongo:latest
    container_name: demo-mongodb
    ports:
      - 27017:27017
    volumes:
      - C:\Users\CompetitiveLin\Documents\Volume\mongodb:/data/db

  nameserver:
    image: apache/rocketmq:4.9.7
    container_name: demo-rocketmq-nameserver
    ports:
      - 9876:9876
    volumes:
      - C:\Users\CompetitiveLin\Documents\Volume\rocketmq\nameserver\logs:/home/rocketmq/logs
    command: sh mqnamesrv

  broker:
    image: apache/rocketmq:4.9.7
    container_name: demo-rocketmq-broker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - C:\Users\CompetitiveLin\Documents\Volume\rocketmq\broker\logs:/home/rocketmq/logs
      - C:\Users\CompetitiveLin\Documents\Volume\rocketmq\broker\store:/home/rocketmq/store
      - C:\Users\CompetitiveLin\Documents\Volume\rocketmq\broker\conf\broker.conf:/home/rocketmq/rocketmq-4.9.7/conf/broker.conf
    environment:
      - JAVA_OPT_EXT=-server -Xms1g -Xmx1g -Xmn512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
    command: sh mqbroker -n nameserver:9876 -c /home/rocketmq/rocketmq-4.9.7/conf/broker.conf
    depends_on:
      - nameserver

  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: demo-rocketmq-dashboard
    ports:
      - 8088:8080
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=nameserver:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    volumes:
      - C:\Users\CompetitiveLin\Documents\Volume\rocketmq\dashboard\tmp:/tmp
    depends_on:
      - nameserver
  canal-server:
    image: canal/canal-server:latest
    container_name: demo-canal-server
    ports:
      - 11111:11111
    environment:
      #      - canal.destinations = example
      - canal.instance.mysql.slaveId=222  # 不能与 server_id 相同
      - canal.instance.master.address=172.19.0.3:3306
      - canal.instance.dbUsername=canal
      - canal.instance.dbPassword=canal
      - canal.serverMode=RocketMQ
      - rocketmq.namesrv.addr=172.19.0.6:9876
      - canal.mq.topic=CanalTopic
    volumes:
      #      - C:\Users\CompetitiveLin\Documents\Volume\canal\conf:/home/admin/canal-server/conf/
      - C:\Users\CompetitiveLin\Documents\Volume\canal\logs:/home/admin/canal-server/logs/
